[mongodb]
mongodb.kimidi.site
[catalogue]
catalogue.kimidi.site
[redis]
redis.kimidi.site
[user]
user.kimidi.site
[cart]
cart.kimidi.site
[frontend]
frontend.kimidi.site
[mysql]
mysql.kimidi.site
[shipping]
shipping.kimidi.site
[rabbitmq]
rabbitmq.kimidi.site
[payment]
payment.kimidi.site

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321